project 'ExemploAula05.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ExemploAula05' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  
  # Pods for ExemploAula05
  
  
  pod 'IconFontsKit', '~> 1.2'

end
